In [1]:
import numpy as np

In [2]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
r = np.ravel(a)
print(r)

[1 2 3 4 5 6 7 8 9]


In [7]:
r = np.ravel(a,order='C')
print(r)

[1 2 3 4 5 6 7 8 9]


In [8]:
r = np.ravel(a,order='F')
print(r)

[1 4 7 2 5 8 3 6 9]


In [9]:
r = np.ravel(a,order='K')
print(r)

[1 2 3 4 5 6 7 8 9]


In [10]:
l = np.log(a)
print(l)

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [11]:
e = np.empty(5)
print(e)

[3.44900708e-307 3.22650139e-307 4.00537740e-307 4.22787121e-307
 0.00000000e+000]


In [12]:
e = np.empty(5,dtype=int)
print(e)

[-1263871056         381           0           0           1]


In [15]:
e1 = np.empty((3,4),order='F')
print(e1)

[[8.09987951e-312 0.00000000e+000 4.11997952e-033 1.74349690e-076]
 [3.16202013e-322 0.00000000e+000 3.92322256e+179 1.42554547e+160]
 [0.00000000e+000 1.46285447e-047 9.28161175e-072 1.16395704e+165]]


In [16]:
e1 = np.empty((3,4),order='C')
print(e1)

[[8.09987951e-312 0.00000000e+000 4.11997952e-033 1.74349690e-076]
 [3.16202013e-322 0.00000000e+000 3.92322256e+179 1.42554547e+160]
 [0.00000000e+000 1.46285447e-047 9.28161175e-072 1.16395704e+165]]


In [18]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [19]:
z = np.zeros(5,dtype=int)
print(z)

[0 0 0 0 0]


In [20]:
z1 = np.zeros([3,3])
print(z1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Ones function

In [21]:
o1 = np.ones(5)
print(o1)

[1. 1. 1. 1. 1.]


In [22]:
o2 = np.ones((2,3),dtype=int)
print(o2)

[[1 1 1]
 [1 1 1]]


# arange() function

In [23]:
ar = np.arange(10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
ar = np.arange(1,11)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
ar = np.arange(1,11,3)
print(ar)

[ 1  4  7 10]
