# Data type of elements

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a.dtype)

int32


In [5]:
print(b.dtype)

int32


In [6]:
c = np.array([(1.1,2.2,3.3),(4.4,5.5,6.6),(7.7,8.8,9.9)])
print(c)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]


In [7]:
print(c.dtype)

float64


In [8]:
d = np.array([('a','b','c'),('d','e','f')])
print(d)
print(d.dtype)

[['a' 'b' 'c']
 ['d' 'e' 'f']]
<U1


In [9]:
print(b.size)

9


In [10]:
print(d.size)

6


In [11]:
print(b.shape)

(3, 3)


In [12]:
print(a.shape)

(5,)


In [17]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#print(a1)

r = a1.reshape(3,4)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Max() function

In [18]:
print(b.max())

9


# Min Function

In [19]:
print(b.min())

1


# linspace

In [20]:
ls = np.linspace(1,10)
print(ls)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [21]:
ls = np.linspace(1,10,num=20)
print(ls)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [22]:
ls = np.linspace(1,10,endpoint=False)
print(ls)

[1.   1.18 1.36 1.54 1.72 1.9  2.08 2.26 2.44 2.62 2.8  2.98 3.16 3.34
 3.52 3.7  3.88 4.06 4.24 4.42 4.6  4.78 4.96 5.14 5.32 5.5  5.68 5.86
 6.04 6.22 6.4  6.58 6.76 6.94 7.12 7.3  7.48 7.66 7.84 8.02 8.2  8.38
 8.56 8.74 8.92 9.1  9.28 9.46 9.64 9.82]


In [23]:
ls = np.linspace(1,10,endpoint=False,retstep=True)
print(ls)

(array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82]), 0.18)


In [25]:
ls = np.linspace(1,10,endpoint=False,retstep=True,axis=0)
print(ls)

(array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82]), 0.18)


In [26]:
ls = np.linspace(1,10,endpoint=False,retstep=True)
print(ls)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [27]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b.sum())

45


In [29]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)
print(b.sum(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [30]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)
print(b.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


In [31]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)
print(b.sum(axis=1,dtype=float))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6. 15. 24.]


In [32]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)
print(b.sum(keepdims=True))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[45]]


In [33]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)
print(b.sum(keepdims=True,initial=20))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[65]]


In [34]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)
print(a+b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [35]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)
print(a/b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Square root

In [37]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
sq = np.sqrt(a)
print(sq)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


# Standard Deviation

In [38]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
sd = np.std(a)
print(sd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.581988897471611


In [39]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
sd = np.std(a,axis=0)
print(sd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2.44948974 2.44948974 2.44948974]


In [40]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
sd = np.std(a,axis=1)
print(sd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0.81649658 0.81649658 0.81649658]


In [42]:
a = np.array([1,2,3,4,5])
print(a)
b = np.array([6,7,8,9,10])
print(b)
vs = np.vstack((a,b))
print(vs)

[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
a1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a1)
b1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b1)
vs1 = np.vstack((a1,b1))
print(vs1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
a = np.array([1,2,3,4,5])
print(a)
b = np.array([6,7,8,9,10])
print(b)
hs = np.hstack((a,b))
print(hs)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [46]:
a1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a1)
b1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b1)
hs1 = np.hstack((a1,b1))
print(hs1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [47]:
e = np.exp(3)
print(e)

20.085536923187668


In [48]:
e1 = np.exp(b)
print(e1)

[  403.42879349  1096.63315843  2980.95798704  8103.08392758
 22026.46579481]
